[Pack]
Name = SnippingToolEx
Author = ware_1234
; Small typo fix
Version = 1.0.0.1
Preview = preview.png
Readme = README.txt
; Support 7 and later
MinBuild = 7601
MaxBuild = 99999999

[Files]
%SystemRoot%\System32\en-US\SnippingTool.exe.mui = Files\en-US\SnippingTool.exe.mui
%SystemRoot%\System32\SnippingTool.exe = Files\SnippingTool.exe